spring:
  profiles:
    group:
      "test" : "localDB, devPort, secret, web-mvc, jpa-config"
      "local": "localDB, devPort, secret, web-mvc, jpa-config"
      "dev": "devDB, devPort, secret, web-mvc, jpa-config"
      "prod": "prodDB, prodPort, secret, web-mvc, jpa-config"

---

spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "devDB"

  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "prodDB"

  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9001

---

spring:
  config:
    activate:
      on-profile: "secret"

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in: ${JWT_EXPIRED_IN}

---

spring:
  config:
    activate:
      on-profile: "web-mvc"

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  messages:
    basename: errors

---
spring:
  config:
    activate:
      on-profile: "jpa-config"

  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

---

logging:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind:


